# Generated by Django 2.1 on 2018-08-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_save', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('token_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='link_save.User')),
            ],
        ),
    ]
