# Generated by Django 2.1 on 2018-08-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_save', '0002_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
